
variables:
  GIT_COMMIT: $(Build.SourceVersion)
  GIT_BRANCH: $(Build.SourceBranchName)
  serviceConnection: sohk1997
  imageName: my-budgeting-app:$(GIT_COMMIT)

trigger:
- master

steps:
  - task: Docker@2
    displayName: Build image
    inputs:
      repository: $(imageName)
      command: build
      Dockerfile: Dockerfile
  - task: Docker@2
    displayName: Push image
    inputs:
      containerRegistry: $(serviceConnection)
      repository: $(imageName)
      command: push
      tags: |
        latest
        $(GIT_COMMIT)
