variables:
  imageTag: $(Build.SourceVersion)
  dockerHub: sohk1997.azurecr.io
  imageName: my-budgeting-app

trigger:
- master

stages:
- stage: build
  displayName: Build
  jobs:
  - job: Build
    displayName: Build and publish to acr
    steps:
    - task: Docker@2
      displayName: Login registry
      inputs:
        containerRegistry: $(dockerHub)
        command: login
    - task: Docker@2
      displayName: Build image
      inputs:
        repository: $(imageName)
        command: build
        Dockerfile: Dockerfile
        tags: |
          latest
          $(imageTag)
    - task: Docker@2
      displayName: Push image
      inputs:
        containerRegistry: $(dockerHub)
        repository: $(imageName)
        command: push
        tags: |
          latest
          $(imageTag)
- stage: Deploy
  displayName: Deploy
  dependsOn: build
  jobs:
  - job: Deploy
    displayName: deploy
    pool:
      vmImage: ubuntu-16.04
    steps:
    - task: Bash@3
      displayName: Envsubst
      inputs:
        script: envsubst < main.yml > my-main.yml
        targetType: inline
      env:
        imageTag: $(Build.SourceVersion)
        dockerHub: sohk1997.azurecr.io
        imageName: my-budgeting-app
    - task: Bash@3
      displayName: Debug
      inputs:
        script: cat my-main.yml
        targetType: inline
    - bash: cat my-main.yml
      targetType: inline
    - task: Kubernetes@1
      inputs:
        connectionType: 'Kubernetes Service Connection'
        kubernetesServiceEndpoint: 'my-budgeting-app-nonprod'
        command: 'apply'
        secretType: 'dockerRegistry'
        containerRegistryType: 'Azure Container Registry'
        outputFormat: 'yaml'
        arguments: -f my-main.yml
