
variables:
  GIT_COMMIT: $(Build.SourceVersion)
  GIT_BRANCH: $(Build.SourceBranchName)
  dockerHub: sohk1997.azurecr.io
  imageName: my-budgeting-app

trigger:
- master

steps:
  - task: Docker@2
    displayName: Build image
    inputs:
      repository: $(imageName)
      command: build
      Dockerfile: Dockerfile
  - task: Docker@2
    displayName: Push image
    inputs:
      containerRegistry: $(dockerHub)
      repository: $(imageName)
      command: push
      tags: |
        latest
        $(GIT_COMMIT)
